### ISSUE TITLE
WorldManagement, importing a World

### ISSUE THREAD

**Issue by lail0ken** [DouglasDwyer/IntegratedMinecraftServer#2] opened 2020-06-26 11:36 UTC
Unable to workout how you can import a World to use with a Server.
There seems to be no option, and if you create the server with the World name, you just get a duplicate.

**Comment by DouglasDwyer** [comment] 2020-06-26 13:33
Hello,
The "Upload World" button is supposed to be on the top of the World Management page, as seen in this screenshot.  Does it appear there for you?
![Screenshot](https://user-images.githubusercontent.com/35274124/85862627-07aa5b00-b790-11ea-99b9-c11bd2bd463f.png)

**Comment by lail0ken** [comment] 2020-06-27 04:12
It does, 
I uploaded and it is there, 
my problem was having it loaded on a server.

I cannot work out how I can access that uploaded world.
If you could choose the world with a Server that would do the trick,
 but there does not seem to be a way in the interface to loadup a world.

**Comment by DouglasDwyer** [comment] 2020-06-27 14:03
Ah!  To do that, you need to click the three dots next to the world name and select "set as server world" with the server you want to modify selected in the top right.  I hope this helps - I am going to close this issue for now, but feel free to open another issue if that doesn't work as intended.

**Closed by DouglasDwyer** 2020-06-27 14:03 UTC
Labels: question
